# Generated by Django 4.0.3 on 2022-03-07 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_name', models.CharField(default='python', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queson', models.CharField(max_length=200)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cores')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corectAnser', models.CharField(max_length=200)),
                ('qution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.question')),
            ],
        ),
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opetion1', models.CharField(max_length=200)),
                ('opetion2', models.CharField(max_length=200)),
                ('opetion3', models.CharField(max_length=200)),
                ('opetion4', models.CharField(max_length=200)),
                ('qution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.question')),
            ],
        ),
    ]
